version: '3.9'

services:
  app:
    image: node:14
    container_name: app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install && node app.js"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always

    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db

    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: